p = 'qc/features.py'; s = open(p, encoding='utf-8').read()
s = s.replace("CACHE = 'cache/fields'", "CACHE = os.environ.get('QC_CACHE', 'cache/fields')")
open(p, 'w', encoding='utf-8').write(s)
p = 'qc/segment.py'; s = open(p, encoding='utf-8').read()
s = s.replace("import numpy as np\n", "import os\n\nimport numpy as np\n", 1)
s = s.replace("def segment(bse, px_nm, f_pore=0.5, f_bright=0.5):", "F_PORE = float(os.environ.get('QC_FPORE', 0.5))\nF_BRIGHT = float(os.environ.get('QC_FBRIGHT', 0.5))\n\n\ndef segment(bse, px_nm, f_pore=F_PORE, f_bright=F_BRIGHT):")
open(p, 'w', encoding='utf-8').write(s)
p = 'qc/pipeline.py'; s = open(p, encoding='utf-8').read()
s = s.replace("REF_PATH = 'cache/reference.json'\nREPORTS = 'reports'", "REF_PATH = os.environ.get('QC_REF', 'cache/reference.json')\nREPORTS = os.environ.get('QC_REPORTS', 'reports')")
s = s.replace("    json.dump(_clean(ref), open(REF_PATH, 'w'), indent=1)", "    os.makedirs(os.path.dirname(REF_PATH) or '.', exist_ok=True)\n    json.dump(_clean(ref), open(REF_PATH, 'w'), indent=1)")
open(p, 'w', encoding='utf-8').write(s)
print('ok')
